In [ ]:
import pandas as pd 
import numpy as np 
import seaborn as sbn
import matplotlib.pyplot as plt

In [ ]:
#!pip install pandas --loading Pandas

In [2]:
import pandas as pd

pandas is a python for data manipulation and analysis 
pandas allow to analys big data and make conclusions based on statistical theories 
pandas can clean messy data sets and make them readable and relevant 
relevant data is very important in data science 

pandas answers
correlation between two or more column 
average value

In [3]:
#ID, NAME,GENDER,AGE
data= ({"ID":101,"Name": "cosmas","Gender": "male","Age":25},
       {"ID":102,"Name": "John","Gender": "male","Age":20}, 
       {"ID":103,"Name": "Joy","Gender": "Female","Age":30})
print(data)

({'ID': 101, 'Name': 'cosmas', 'Gender': 'male', 'Age': 25}, {'ID': 102, 'Name': 'John', 'Gender': 'male', 'Age': 20}, {'ID': 103, 'Name': 'Joy', 'Gender': 'Female', 'Age': 30})

In [4]:
df = pd.DataFrame(data)
print("DataFrame:")
print(df)
print()

DataFrame:
    ID    Name  Gender  Age
0  101  cosmas    male   25
1  102    John    male   20
2  103     Joy  Female   30

In [9]:
df.head()

    ID    Name  Gender  Age
0  101  cosmas    male   25
1  102    John    male   20
2  103     Joy  Female   30

In [ ]:
#check the data types 
df.info()

In [ ]:
#check the data types 
df.dtypes

ID         int64
Name      object
Gender    object
Age        int64
dtype: object

In [ ]:
#check the missing Values 
#missing values shows True
df.isnull()

ID        0
Name      0
Gender    0
Age       0
dtype: int64

In [ ]:
#check the missing Values 
#missing values shows True
df.isnull().sum()

ID        0
Name      0
Gender    0
Age       0
dtype: int64

In [ ]:
#check each data 
df["Name"]

0    cosmas
1      John
2       Joy
Name: Name, dtype: object

In [18]:
df.loc [1, "Age"]

np.int64(20)

In [ ]:
# recall the data name in the data 
df.iloc [1, 1]

'John'

In [ ]:
#handling missing values 
df.dropna()
#Replace column Age fill the na in Column Age with the Mean 
df['Age'].fillna(df['Age'].mean())

    ID    Name  Gender  Age
0  101  cosmas    male   25
1  102    John    male   20
2  103     Joy  Female   30

In [ ]:
#data loading 
#import data --use the read.csv--read.exc
pd.read_csv('df.cs') #---importing data in the excisting desktop

In [21]:
import os 
os.getcwdb()

b'c:\\Users\\user\\Desktop\\AfriCDSA'

In [ ]:
#exporting the data from python to other external saves 
#writing 
df.to_csv('practical.csv')